services:
  backend:
    build: ./backend
    command: uvicorn src.app:app --host 0.0.0.0 --reload --port 8000
    container_name: backend
    volumes:
      - ./backend:/backend
    env_file: ".env.dev"
    ports:
      - "8000:8000"
    depends_on:
      - backend-db

  backend-worker:
    build: ./backend
    command: [ 'celery', '-A', 'src.worker', 'worker', '-l', 'info' ]
    container_name: backend-worker
    env_file: ".env.dev"
    volumes:
      - ./backend:/backend
    depends_on:
      - backend-db

  backend-db:
    image: postgres:latest
    container_name: backend-db
    env_file: ".env.dev"
    volumes:
      - backend-db-volume:/var/lib/postgresql
    ports:
      - "5433:5432"

  backend-redis:
    image: redis:latest
    container_name: backend-redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file: "./frontend/.env.dev"

volumes:
  backend-db-volume:
