[pytest]
testpaths = tests

asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session

markers =
    unit: Fast tests with no dependencies (Domain/Application layer)
    integration: Slower tests involving databases or APIs (Infrastructure layer)
    api: Full-slice tests for FastAPI endpoints (Presentation layer)
addopts = -v -ra